[package]
  name    = "aeth-devkit-core"
  version.workspace = true
  edition.workspace = true
  publish.workspace = true

[lib]
  name = "aeth_devkit_core"

[features]
  test-util = []

[dependencies]
  anyhow     = { workspace = true }
  base64     = { workspace = true }
  pep440_rs  = { workspace = true }
  regex      = { workspace = true }
  serde      = { workspace = true, features = ["derive"] }
  serde_json = { workspace = true }
  tempfile   = { workspace = true }
  toml_edit  = { workspace = true }
  ureq       = { workspace = true }
