[package]
  name    = "aeth-devkit"
  version.workspace = true
  edition.workspace = true
  publish.workspace = true

[[bin]]
  name = "devkit"
  path = "src/main.rs"

[dependencies]
  aeth-devkit-lock  = { workspace = true }
  aeth-devkit-setup = { workspace = true }
  anyhow            = { workspace = true }
  clap              = { workspace = true }
